### ISSUE TITLE
A few outdated spec links

### ISSUE THREAD

**Issue by domenic** [nolanlawson/html5workertest#6]
- https://www.w3.org/TR/service-workers/#cache should be https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#cache-objects
- https://www.w3.org/TR/FileAPI/#FileReaderSync should be https://w3c.github.io/FileAPI/#dfn-FileReaderSync
- http://www.ecma-international.org/ecma-262/6.0/#sec-promise-objects should be https://tc39.github.io/ecma262/#sec-promise-objects
- https://www.w3.org/TR/requestidlecallback/ should be https://w3c.github.io/requestidlecallback/
- https://github.com/DeveloperToolsWG/console-object/blob/master/api.md should be https://console.spec.whatwg.org/
- https://www.w3.org/TR/encoding/ should be https://encoding.spec.whatwg.org/ (or maybe https://encoding.spec.whatwg.org/#api)

Overall really solid; avoided many outdated specs that clog up Google search results. Just remember, "/TR/ stands for trash".

**Comment by nolanlawson** [comment]
lol, I always wondered what TR stood for. ;)

Yeah these links are in `apiTests.js`; I'll update the ones you pointed out, thanks!

**Comment by JakeChampion** [comment]
Thanks for this @domenic. I never knew what TR stood for, thanks for the explanation, now I know what else to look out for :-)
