### ISSUE TITLE
Why document Firefox OS-only APIs (DOMRequest/DOMCursor)?

### ISSUE THREAD

**Issue by domenic** [nolanlawson/html5workertest#7]
Seems uninteresting.

**Comment by nolanlawson** [comment]
TBH I just looked through the Edge WebIDL and the [MDN page on functions and classes available to workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers).

Despite the name, my goal with this project is more to provide a resource for web devs to educate them about what APIs aren't available inside of workers; hence why some APIs that might not be on the standards track (DOMCursor, setImmediate, etc.) are in there. As you point out in #8 the red X might be a bit misleading though. Let's move discussion to that issue.
