### ISSUE TITLE
Notate which APIs *should* be exposed in workers, per spec?

### ISSUE THREAD

**Issue by domenic** [nolanlawson/html5workertest#8]
E.g. LocalStorage/SessionStorage/WebSQL are not, per spec, supposed to be there. So the red "X" is a bit misleading. Same for most things with red Xs all along the way, actually.

**Comment by nolanlawson** [comment]
Yeah as I say in https://github.com/nolanlawson/html5workertest/issues/7#issuecomment-237894656 my goal here is mostly education. Possibly we should replace the red Xs for things like localStorage, setImmediate, and DOMCursor with something less alerty-y (yellow circle or something?) plus some information on _why_ the APIs aren't in there.

E.g. WebSQL was dropped from both Chrome and Safari; we could link back to the relevant Chromium issue where this was discussed. OTOH just not mentioning WebSQL at all does a disservice to web developers who might be wondering why e.g. PouchDB/LocalForage doesn't work inside of a Safari web worker.
