### ISSUE TITLE
Update to Firefox 48 and Chrome 52

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/html5workertest#9]
These are out now; it should just be a matter of re-running the tests, but localtunnel seems to be failing me due to firewall issues on Travis.

**Comment by JakeChampion** [comment]
Nope, localtunnel.me is having issues itself, not the firewall settings on travis. This has affected many of my projects, even running localtunnel on my machine fails more than it succeeds.

**Comment by nolanlawson** [comment]
Dang. I may need to switch to running my own localtunnel server. ☹ Note I already tried ngrok, but they throttled me...

**Comment by JakeChampion** [comment]
That's what I'm doing on an ad-hock basis. It's either that or look at the localtunnel server code and try to locate the problematic branch of code.

**Comment by nolanlawson** [comment]
Fixed.
